<?php

declare(strict_types=1);

namespace IfCastle\Configurator\Toml;

use Devium\Toml\TomlError;
use IfCastle\DI\Exceptions\ConfigException;
use IfCastle\Exceptions\RuntimeException;
use IfCastle\ServiceManager\RepositoryStorages\ServiceCollectionWriterInterface;
use IfCastle\ServiceManager\ServiceConfigReaderTrait;
use IfCastle\ServiceManager\ServiceConfigWriterTrait;

class ServiceConfigWriter extends ConfigTomlMutable implements ServiceCollectionWriterInterface
{
    use ServiceConfigReaderTrait;
    use ServiceConfigWriterTrait;

    public function __construct(string $appDir, bool $isReadOnly = false)
    {
        parent::__construct($appDir . '/services.toml', $isReadOnly);
    }

    /**
     * @throws RuntimeException
     * @throws TomlError
     * @throws ConfigException
     * @throws \ErrorException
     */
    #[\Override]
    public function saveRepository(): void
    {
        // remove the empty nodes
        foreach ($this->data as $key => $value) {
            if ($value === []) {
                unset($this->data[$key]);
            }
        }

        $this->save();
    }

    #[\Override]
    protected function afterBuild(string $content): string
    {
        $at                         = \date('Y-m-d H:i:s');
        $comment                    = <<<TOML
            # ================================================================
            # This file is generated by the IfCastle Configurator
            # at $at
            # Do not edit this file manually!
            # ================================================================
            
            TOML;
        return $comment . $content;
    }
}
